apiVersion: apps/v1
kind: Deployment

metadata: 
  name: jooo-deployment

spec: 
  selector: 
    matchLabels: 
      app: youssef
  replicas: 3   
  template: 
    metadata:
      name: first-pod
      labels:
        app: youssef
    spec: 
      containers:
        - image: nginx:apline
          name: nginx-container
          resources:
            limits:
              memory: "512Mi"
              cpu: "1"