apiVersion: v1
kind: pod
metadata:
  name: my-web-app 
spec: 
  containers:
    - name: my-nginx-app
      image: index/nginx-web
      imagePullPolicy: IfNotPresent
      ports: 
        - containerPort: 80
        
      